alertmanager:
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: { }
    labels: { }
    hosts: [ ]
    paths: [ ]
    pathType: ImplementationSpecific
    tls: [ ]
    