prometheus:
  prometheusSpec:
    disableCompaction: false
    apiserverConfig: { }
    scrapeInterval: ""
    scrapeTimeout: ""
    evaluationInterval: ""
    web: { }
    enableFeatures: [ ]
    listenLocal: false
    enableAdminAPI: false